spring.application.name=Lab8
# Cấu hình kết nối MS SQL Server
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=java5;encrypt=true;trustServerCertificate=true;
spring.datasource.username=sa
spring.datasource.password=123

# Cấu hình JPA/Hibernate
spring.jpa.hibernate.ddl-auto=none
spring.jpa.database-platform=org.hibernate.dialect.SQLServerDialect
spring.jpa.show-sql=true